# fly.toml app configuration file generated for recall-checker-4fe8xq on 2026-07-07T18:35:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recall-checker-4fe8xq'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'canary'
  max_unavailable = 0.5

[env]
  LOG_LEVEL = 'info'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
